In [166]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [167]:
with open("text_data.txt","r") as f:
  text = f.read()

In [168]:
print(text)

Good morning! How did you sleep last night? Did you have any interesting dreams?
Hey there! I was just thinking about you the other day. How have you been doing?
What a beautiful day outside! Have you had a chance to enjoy the weather yet?
I'm so glad we finally have some time to catch up. What's new in your life?
Could you believe how crowded the supermarket was this morning? It was insane!
I just wanted to say thank you again for helping me move last weekend. You're amazing!
How was your weekend? Did you end up going to that concert you mentioned?
I'm really sorry I'm running late. Traffic is absolutely terrible this morning.
What do you feel like having for lunch today? I'm craving something spicy myself.
Have you seen the new coffee shop that opened down the street? It looks really nice.
I can't believe how fast this week has gone by. Is it Friday already?
Would you like to grab dinner sometime this week? I know a great new restaurant.
How's your family doing? I heard your sister j

In [169]:

type(text)

str

In [170]:
import tensorflow as tf
from tensorflow import keras

In [171]:
from tensorflow.keras.preprocessing.text import Tokenizer


In [172]:
tokenizer = Tokenizer()

In [173]:
tokenizer.fit_on_texts([text])

In [174]:
len(tokenizer.word_index.keys())

2478

In [175]:
tokenizer.word_index

{'i': 1,
 'the': 2,
 'to': 3,
 'my': 4,
 'and': 5,
 "i'm": 6,
 'a': 7,
 'you': 8,
 'is': 9,
 'that': 10,
 'me': 11,
 'for': 12,
 'in': 13,
 'like': 14,
 'about': 15,
 'of': 16,
 'how': 17,
 'your': 18,
 'been': 19,
 'this': 20,
 'have': 21,
 'so': 22,
 'it': 23,
 'with': 24,
 'feel': 25,
 'since': 26,
 'was': 27,
 "what's": 28,
 'now': 29,
 'from': 30,
 'making': 31,
 'they': 32,
 'on': 33,
 "i've": 34,
 'at': 35,
 'their': 36,
 'really': 37,
 'completely': 38,
 'mine': 39,
 'out': 40,
 'everything': 41,
 'just': 42,
 'new': 43,
 'by': 44,
 'when': 45,
 "can't": 46,
 'be': 47,
 'are': 48,
 'what': 49,
 'absolutely': 50,
 'has': 51,
 'do': 52,
 'love': 53,
 'could': 54,
 'know': 55,
 'favorite': 56,
 'them': 57,
 'up': 58,
 'apparently': 59,
 "don't": 60,
 'time': 61,
 'life': 62,
 'believe': 63,
 'would': 64,
 'being': 65,
 'want': 66,
 'as': 67,
 'thinking': 68,
 'everyone': 69,
 'inside': 70,
 'all': 71,
 "it's": 72,
 'wanted': 73,
 'though': 74,
 'never': 75,
 'every': 76,
 'through

In [176]:
# converting into numbers

In [177]:
for sentence in text.split('\n'):
  if sentence.strip():
    print(tokenizer.texts_to_sequences([sentence])[0])

[120, 165, 17, 104, 8, 190, 136, 126, 104, 8, 21, 90, 145, 1262]
[786, 146, 1, 27, 42, 68, 15, 8, 2, 434, 214, 17, 21, 8, 19, 108]
[49, 7, 99, 214, 310, 21, 8, 177, 7, 435, 3, 787, 2, 191, 788]
[6, 22, 436, 115, 121, 21, 166, 61, 3, 437, 58, 28, 43, 13, 18, 62]
[54, 8, 63, 17, 556, 2, 789, 27, 20, 165, 23, 27, 1263]
[1, 42, 73, 3, 215, 147, 8, 116, 12, 790, 11, 438, 136, 178, 362, 192]
[17, 27, 18, 178, 104, 8, 557, 58, 244, 3, 10, 558, 8, 1264]
[6, 37, 439, 6, 193, 559, 560, 9, 50, 363, 20, 165]
[49, 52, 8, 25, 14, 216, 12, 791, 127, 6, 792, 86, 1265, 179]
[21, 8, 245, 2, 43, 246, 247, 10, 440, 137, 2, 441, 23, 279, 37, 442]
[1, 46, 63, 17, 561, 20, 155, 51, 1266, 44, 9, 23, 1267, 217]
[64, 8, 14, 3, 443, 248, 1268, 20, 155, 1, 55, 7, 156, 43, 311]
[100, 18, 364, 108, 1, 194, 18, 1269, 42, 177, 7, 562, 312]
[6, 22, 313, 127, 1, 793, 58, 148, 157, 559, 138, 10, 43, 563, 33, 1270]
[104, 8, 280, 15, 2, 365, 794, 444, 35, 2, 795, 20, 178, 115, 105, 249]
[28, 18, 281, 12, 2, 445, 48, 8, 44

In [178]:
# makint the input sequences

In [179]:
input_sequences = []
for sentence in text.split('\n'):
  if sentence.strip():
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1,len(tokenized_sentence)):
      input_sequences.append(tokenized_sentence[:i+1])

In [180]:
# for 5 the next word will be 81
# for 5 and 81 the next word will be 21
# for 5,81and 21 the next word will be 219

"""
so if X = 5 then y = 81
if X = 5,81 then y = 21
if X = 51,81,21 then y = 219
"""

'\nso if X = 5 then y = 81\nif X = 5,81 then y = 21\nif X = 51,81,21 then y = 219\n'

In [181]:
input_sequences

[[120, 165],
 [120, 165, 17],
 [120, 165, 17, 104],
 [120, 165, 17, 104, 8],
 [120, 165, 17, 104, 8, 190],
 [120, 165, 17, 104, 8, 190, 136],
 [120, 165, 17, 104, 8, 190, 136, 126],
 [120, 165, 17, 104, 8, 190, 136, 126, 104],
 [120, 165, 17, 104, 8, 190, 136, 126, 104, 8],
 [120, 165, 17, 104, 8, 190, 136, 126, 104, 8, 21],
 [120, 165, 17, 104, 8, 190, 136, 126, 104, 8, 21, 90],
 [120, 165, 17, 104, 8, 190, 136, 126, 104, 8, 21, 90, 145],
 [120, 165, 17, 104, 8, 190, 136, 126, 104, 8, 21, 90, 145, 1262],
 [786, 146],
 [786, 146, 1],
 [786, 146, 1, 27],
 [786, 146, 1, 27, 42],
 [786, 146, 1, 27, 42, 68],
 [786, 146, 1, 27, 42, 68, 15],
 [786, 146, 1, 27, 42, 68, 15, 8],
 [786, 146, 1, 27, 42, 68, 15, 8, 2],
 [786, 146, 1, 27, 42, 68, 15, 8, 2, 434],
 [786, 146, 1, 27, 42, 68, 15, 8, 2, 434, 214],
 [786, 146, 1, 27, 42, 68, 15, 8, 2, 434, 214, 17],
 [786, 146, 1, 27, 42, 68, 15, 8, 2, 434, 214, 17, 21],
 [786, 146, 1, 27, 42, 68, 15, 8, 2, 434, 214, 17, 21, 8],
 [786, 146, 1, 27, 42, 68

In [182]:
# finding the maximun length sequence

In [183]:
max_len = max([len(x) for x in input_sequences])
max_len

51

In [184]:
# applying padding
# padding by adding zero before all the list for making same shape

In [185]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [186]:
padded_input_sequences

array([[   0,    0,    0, ...,    0,  120,  165],
       [   0,    0,    0, ...,  120,  165,   17],
       [   0,    0,    0, ...,  165,   17,  104],
       ...,
       [   0,    0,   20, ...,   42,   12,   69],
       [   0,   20,  184, ...,   12,   69, 2478],
       [  20,  184,  271, ...,   69, 2478,   94]], dtype=int32)

In [187]:
padded_input_sequences.shape

(13216, 51)

In [188]:
# getting x and y for feature and target column

In [189]:
X = padded_input_sequences[:,:-1] # it will not take the last value (Which is the target (or X))
X

array([[   0,    0,    0, ...,    0,    0,  120],
       [   0,    0,    0, ...,    0,  120,  165],
       [   0,    0,    0, ...,  120,  165,   17],
       ...,
       [   0,    0,   20, ...,    5,   42,   12],
       [   0,   20,  184, ...,   42,   12,   69],
       [  20,  184,  271, ...,   12,   69, 2478]], dtype=int32)

In [190]:
X.shape

(13216, 50)

In [191]:
y = padded_input_sequences[:,-1] # taking the last value as a output(or y)

In [192]:
y

array([ 165,   17,  104, ...,   69, 2478,   94], dtype=int32)

In [193]:
y.shape

(13216,)

In [194]:
len(tokenizer.word_index)

2478

In [195]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=13216)


In [196]:
y.shape

(13216, 13216)

In [197]:
print(y[512])

[0. 0. 0. ... 0. 0. 0.]


In [198]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [199]:
model = Sequential()

In [200]:
"""
model.add(Embedding(13216, output_dim=200,mask_zero=True, input_shape=(42,)))
model.add(LSTM(128,return_sequences=True,activation='relu'))
model.add(LSTM(256,return_sequences=True))
model.add(LSTM(128))
model.add(Dense(13216, activation='softmax'))"""

"\nmodel.add(Embedding(13216, output_dim=200,mask_zero=True, input_shape=(42,)))\nmodel.add(LSTM(128,return_sequences=True,activation='relu'))\nmodel.add(LSTM(256,return_sequences=True))\nmodel.add(LSTM(128))\nmodel.add(Dense(13216, activation='softmax'))"

In [201]:
model.add(Embedding(13216, output_dim=200, input_shape=(42,)))
model.add(LSTM(128, return_sequences=True, activation="tanh"))
model.add(LSTM(256, return_sequences=True, activation="tanh"))
model.add(LSTM(128, activation="tanh"))
model.add(Dense(13216, activation="softmax"))


In [202]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ (None, 42, 200)        │     2,643,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_12 (LSTM)                  │ (None, 42, 128)        │       168,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_13 (LSTM)                  │ (None, 42, 256)        │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_14 (LSTM)                  │ (None, 128)            │       197,120 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 13216)          │     1,704,864 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,107,872 (19.48 MB)

 Trainable params: 5,107,872 (19.48 MB)

 Non-trainable params: 0 (0.00 B)

In [203]:
model.compile(optimizer="adam",loss='categorical_crossentropy',metrics=['accuracy'])

In [207]:
model.fit(X,y,epochs=70)

Epoch 1/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.1490 - loss: 4.6382
Epoch 2/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.1633 - loss: 4.4858
Epoch 3/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - accuracy: 0.1795 - loss: 4.3060
Epoch 4/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 10s 16ms/step - accuracy: 0.1902 - loss: 4.1667
Epoch 5/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - accuracy: 0.2032 - loss: 4.0323
Epoch 6/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.2171 - loss: 3.8892
Epoch 7/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.2374 - loss: 3.7513
Epoch 8/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.2399 - loss: 3.6305
Epoch 9/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.2583 - loss: 3.4856
Epoch 10/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 7s 16ms/step - accuracy: 0.2724 - loss: 3.3757
Epoch 11/70
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.2892 - loss: 3.2597
Epoch 12/70
413/413 ━━━━━━━━━━━━━━━━━━

In [216]:
import time
text = "this"

for i in range(20):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
this burning
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
this burning resentment
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
this burning resentment is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
this burning resentment is like
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
this burning resentment is like acid
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
this burning resentment is like acid rain
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
this burning resentment is like acid rain falling
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
this burning resentment is like acid rain falling on
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
this burning resentment is like acid rain falling on my
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
this burning resentment is like acid rain falling on my parade
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
this burning resentment is like acid rain falling on my parade and
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
this burning resentment is like acid rain falling on my parade and ruining
1/1 ━