# Next Word Predictor using Long-Short-Term-Memory-(LSTM)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
with open("text_data.txt","r") as f:
  text = f.read()

In [3]:
print(text)

Good morning! How did you sleep last night? Did you have any interesting dreams?
Hey there! I was just thinking about you the other day. How have you been doing?
What a beautiful day outside! Have you had a chance to enjoy the weather yet?
I'm so glad we finally have some time to catch up. What's new in your life?
Could you believe how crowded the supermarket was this morning? It was insane!
I just wanted to say thank you again for helping me move last weekend. You're amazing!
How was your weekend? Did you end up going to that concert you mentioned?
I'm really sorry I'm running late. Traffic is absolutely terrible this morning.
What do you feel like having for lunch today? I'm craving something spicy myself.
Have you seen the new coffee shop that opened down the street? It looks really nice.
I can't believe how fast this week has gone by. Is it Friday already?
Would you like to grab dinner sometime this week? I know a great new restaurant.
How's your family doing? I heard your sister j

In [4]:
type(text)

str

In [5]:
import tensorflow as tf
from tensorflow import keras

In [6]:
from tensorflow.keras.preprocessing.text  import Tokenizer

In [7]:
# creating an object of tokenizer class
tokenizer = Tokenizer(oov_token='') # if any word came out side the train data it will simple print nothing

In [8]:
tokenizer.fit_on_texts([text])

In [9]:
len(tokenizer.word_index.keys())

2479

In [10]:
tokenizer.word_index

{'': 1,
 'i': 2,
 'the': 3,
 'to': 4,
 'my': 5,
 'and': 6,
 "i'm": 7,
 'a': 8,
 'you': 9,
 'is': 10,
 'that': 11,
 'me': 12,
 'for': 13,
 'in': 14,
 'like': 15,
 'about': 16,
 'of': 17,
 'how': 18,
 'your': 19,
 'been': 20,
 'this': 21,
 'have': 22,
 'so': 23,
 'it': 24,
 'with': 25,
 'feel': 26,
 'since': 27,
 'was': 28,
 "what's": 29,
 'now': 30,
 'from': 31,
 'making': 32,
 'they': 33,
 'on': 34,
 "i've": 35,
 'at': 36,
 'their': 37,
 'really': 38,
 'completely': 39,
 'mine': 40,
 'out': 41,
 'everything': 42,
 'just': 43,
 'new': 44,
 'by': 45,
 'when': 46,
 "can't": 47,
 'be': 48,
 'are': 49,
 'what': 50,
 'absolutely': 51,
 'has': 52,
 'do': 53,
 'love': 54,
 'could': 55,
 'know': 56,
 'favorite': 57,
 'them': 58,
 'up': 59,
 'apparently': 60,
 "don't": 61,
 'time': 62,
 'life': 63,
 'believe': 64,
 'would': 65,
 'being': 66,
 'want': 67,
 'as': 68,
 'thinking': 69,
 'everyone': 70,
 'inside': 71,
 'all': 72,
 "it's": 73,
 'wanted': 74,
 'though': 75,
 'never': 76,
 'every': 77,


In [11]:
# converting into numbers

In [12]:
for sentence in text.split('\n'):
  if sentence.strip():
    print(tokenizer.texts_to_sequences([sentence])[0])

[121, 166, 18, 105, 9, 191, 137, 127, 105, 9, 22, 91, 146, 1263]
[787, 147, 2, 28, 43, 69, 16, 9, 3, 435, 215, 18, 22, 9, 20, 109]
[50, 8, 100, 215, 311, 22, 9, 178, 8, 436, 4, 788, 3, 192, 789]
[7, 23, 437, 116, 122, 22, 167, 62, 4, 438, 59, 29, 44, 14, 19, 63]
[55, 9, 64, 18, 557, 3, 790, 28, 21, 166, 24, 28, 1264]
[2, 43, 74, 4, 216, 148, 9, 117, 13, 791, 12, 439, 137, 179, 363, 193]
[18, 28, 19, 179, 105, 9, 558, 59, 245, 4, 11, 559, 9, 1265]
[7, 38, 440, 7, 194, 560, 561, 10, 51, 364, 21, 166]
[50, 53, 9, 26, 15, 217, 13, 792, 128, 7, 793, 87, 1266, 180]
[22, 9, 246, 3, 44, 247, 248, 11, 441, 138, 3, 442, 24, 280, 38, 443]
[2, 47, 64, 18, 562, 21, 156, 52, 1267, 45, 10, 24, 1268, 218]
[65, 9, 15, 4, 444, 249, 1269, 21, 156, 2, 56, 8, 157, 44, 312]
[101, 19, 365, 109, 2, 195, 19, 1270, 43, 178, 8, 563, 313]
[7, 23, 314, 128, 2, 794, 59, 149, 158, 560, 139, 11, 44, 564, 34, 1271]
[105, 9, 281, 16, 3, 366, 795, 445, 36, 3, 796, 21, 179, 116, 106, 250]
[29, 19, 282, 13, 3, 446, 49, 9,

In [13]:
# makint the input sequences

In [14]:
input_sequences = []
for sentence in text.split('\n'):
  if sentence.strip():
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1,len(tokenized_sentence)):
      input_sequences.append(tokenized_sentence[:i+1])

In [15]:
# for 5 the next word will be 81
# for 5 and 81 the next word will be 21
# for 5,81and 21 the next word will be 219

"""
so if X = 5 then y = 81
if X = 5,81 then y = 21
if X = 51,81,21 then y = 219
"""

'\nso if X = 5 then y = 81\nif X = 5,81 then y = 21\nif X = 51,81,21 then y = 219\n'

In [16]:
input_sequences

[[121, 166],
 [121, 166, 18],
 [121, 166, 18, 105],
 [121, 166, 18, 105, 9],
 [121, 166, 18, 105, 9, 191],
 [121, 166, 18, 105, 9, 191, 137],
 [121, 166, 18, 105, 9, 191, 137, 127],
 [121, 166, 18, 105, 9, 191, 137, 127, 105],
 [121, 166, 18, 105, 9, 191, 137, 127, 105, 9],
 [121, 166, 18, 105, 9, 191, 137, 127, 105, 9, 22],
 [121, 166, 18, 105, 9, 191, 137, 127, 105, 9, 22, 91],
 [121, 166, 18, 105, 9, 191, 137, 127, 105, 9, 22, 91, 146],
 [121, 166, 18, 105, 9, 191, 137, 127, 105, 9, 22, 91, 146, 1263],
 [787, 147],
 [787, 147, 2],
 [787, 147, 2, 28],
 [787, 147, 2, 28, 43],
 [787, 147, 2, 28, 43, 69],
 [787, 147, 2, 28, 43, 69, 16],
 [787, 147, 2, 28, 43, 69, 16, 9],
 [787, 147, 2, 28, 43, 69, 16, 9, 3],
 [787, 147, 2, 28, 43, 69, 16, 9, 3, 435],
 [787, 147, 2, 28, 43, 69, 16, 9, 3, 435, 215],
 [787, 147, 2, 28, 43, 69, 16, 9, 3, 435, 215, 18],
 [787, 147, 2, 28, 43, 69, 16, 9, 3, 435, 215, 18, 22],
 [787, 147, 2, 28, 43, 69, 16, 9, 3, 435, 215, 18, 22, 9],
 [787, 147, 2, 28, 43, 69

In [17]:
# finding the maximun length sequence

In [18]:
max_len = max([len(x) for x in input_sequences])
max_len

51

In [19]:
# applying padding
# padding by adding zero before all the list for making same shape

In [20]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [21]:
padded_input_sequences

array([[   0,    0,    0, ...,    0,  121,  166],
       [   0,    0,    0, ...,  121,  166,   18],
       [   0,    0,    0, ...,  166,   18,  105],
       ...,
       [   0,    0,   21, ...,   43,   13,   70],
       [   0,   21,  185, ...,   13,   70, 2479],
       [  21,  185,  272, ...,   70, 2479,   95]], dtype=int32)

In [22]:
padded_input_sequences.shape

(13216, 51)

In [23]:
# getting x and y for feature and target column

In [24]:
X = padded_input_sequences[:,:-1] # it will not take the last value (Which is the target (or X))
X

array([[   0,    0,    0, ...,    0,    0,  121],
       [   0,    0,    0, ...,    0,  121,  166],
       [   0,    0,    0, ...,  121,  166,   18],
       ...,
       [   0,    0,   21, ...,    6,   43,   13],
       [   0,   21,  185, ...,   43,   13,   70],
       [  21,  185,  272, ...,   13,   70, 2479]], dtype=int32)

In [25]:
X.shape

(13216, 50)

In [26]:
y = padded_input_sequences[:,-1] # taking the last value as a output(or y)

In [27]:
y

array([ 166,   18,  105, ...,   70, 2479,   95], dtype=int32)

In [28]:
y.shape

(13216,)

In [29]:
len(tokenizer.word_index)

2479

In [30]:
vocab = len(tokenizer.word_index.keys()) +1

In [31]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=vocab)


In [32]:
y.shape

(13216, 2480)

In [33]:
print(y[512])

[0. 0. 0. ... 0. 0. 0.]


In [34]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense,Dropout

In [35]:
vocab = len(tokenizer.word_index.keys()) +1
max_length = max([len(x) for x in input_sequences])

In [36]:
print(f"the vocab size of the number of words in the data is {vocab}")
print(f"the maximum lenght of sentences in the data is {max_length}")

the vocab size of the number of words in the data is 2480
the maximum lenght of sentences in the data is 51


In [37]:

"""
FOR Embedding layer:
    input_dim:
    - Meaning: This is the size of the vocabulary, i.e., the number of unique words or tokens in your dataset

    output_dim:
    - Meaning: This specifies the dimensionality of the output embedding vectors for each word.

    input_length:
    - Meaning: This specifies the length of the input sequences to the Embedding layer (i.e., the max number of words per sequence).
"""

'\nFOR Embedding layer:\n    input_dim:\n    - Meaning: This is the size of the vocabulary, i.e., the number of unique words or tokens in your dataset\n\n    output_dim:\n    - Meaning: This specifies the dimensionality of the output embedding vectors for each word.\n\n    input_length:\n    - Meaning: This specifies the length of the input sequences to the Embedding layer (i.e., the max number of words per sequence).\n'

In [38]:
model = Sequential()

In [39]:
# embedding layer
model.add(Embedding(input_dim=2480, output_dim=100, input_shape=(50,))) # or input_dim=vocab,output_dime=100,input_shape=(maxlength-1,)

# first LSTM layer with Dropout
model.add(LSTM(160, return_sequences=True, activation="tanh"))
model.add(Dropout(0.2))

# second LSTM layer with Dropout
model.add(LSTM(300, return_sequences=True, activation="tanh"))
model.add(Dropout(0.2))

# third LSTM layer
model.add(LSTM(300, activation="tanh"))
model.add(Dropout(0.2))

# output Dense layer
model.add(Dense(2480, activation="softmax"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [40]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 50, 100)        │       248,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 50, 160)        │       167,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 50, 160)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 50, 300)        │       553,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 50, 300)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 300)            │       721,200 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 300)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 2480)           │       746,480 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,435,920 (9.29 MB)

 Trainable params: 2,435,920 (9.29 MB)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.compile(optimizer="adam",loss='categorical_crossentropy',metrics=['accuracy'])

In [42]:
model.fit(X, y,epochs=100)

Epoch 1/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 13s 16ms/step - accuracy: 0.0255 - loss: 6.8562
Epoch 2/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.0284 - loss: 6.3049
Epoch 3/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - accuracy: 0.0449 - loss: 6.0921
Epoch 4/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.0564 - loss: 5.7796
Epoch 5/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - accuracy: 0.0869 - loss: 5.4803
Epoch 6/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.0940 - loss: 5.2418
Epoch 7/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 10s 16ms/step - accuracy: 0.1158 - loss: 4.9918
Epoch 8/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 10s 16ms/step - accuracy: 0.1277 - loss: 4.7162
Epoch 9/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.1576 - loss: 4.4436
Epoch 10/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 16ms/step - accuracy: 0.1673 - loss: 4.2493
Epoch 11/100
413/413 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.1786 - loss: 4.0295
Epoch 12/100
413/413 ━━━━

In [43]:
import time
text = "I just wanted"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=51, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 346ms/step
I just wanted to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
I just wanted to say
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
I just wanted to say thank
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
I just wanted to say thank you
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
I just wanted to say thank you for
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
I just wanted to say thank you for being
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
I just wanted to say thank you for being such
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
I just wanted to say thank you for being such a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
I just wanted to say thank you for being such a wonderful
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
I just wanted to say thank you for being such a wonderful friend
